version: 2

sources:
  - name: STANDARD_TILE
    database: GLOBAL_WEATHER_CLIMATE
    schema: STANDARD_TILE
    tables:
      - name: CLIMATOLOGY_DAY
      - name: FORECAST_DAY
      - name: HISTORY_DAY
